#### **Neuron coding using numpy**

In [14]:
inputs = [1,2,3,2.5]
weights = [0.2,0.8,-0.5,1]
biases = 2

import numpy as np

outputs = np.dot(inputs,weights)+biases
print(outputs)



4.8


#### used on layer

In [17]:
inputs = [1.0,2.0,3.0,2.5]
weights = [[0.2,0.8,-0.5,1],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,1]]

# ( 3 * 4 ) ( 4 * 1) = ( 3 * 1) -> ( 3 * 1 ) + ( 1 * 3 ) = ( 3 * 1 )
biases = [2,3.5,1]


layer_outputs = np.dot(weights,inputs) + biases
print(layer_outputs)



[4.8  1.71 3.21]


In [23]:
# batch of inputs 
inputs  = [[1,2,3,0.5],
           [1,2,4,2.5],
           [1,2,3,2]]

weights = [[0.2,0.8,-0.5,1],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,1]]

biases = [2,3,0.5]

import numpy as np



outputs = np.dot(inputs,np.transpose(weights)) + biases
print(outputs)



[[2.8  2.21 0.71]
 [4.3  1.47 2.88]
 [4.3  1.46 2.21]]
