In [3]:
!pip install nnfs

In [5]:
## Dence layer class 

from random import sample
import numpy as np
import matplotlib.pyplot as plt
from nnfs.datasets import spiral_data



class Layer_Dense:
    # layer initialization 
    def __init__(self,n_inputs,n_neurons):
        # initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs,n_neurons)
        # initialize biases 0
        self.biases = np.zeros([1,n_neurons])

    def forward(self,inputs):
        # forward pass
        self.outputs = np.dot(inputs,self.weights) + self.biases

X , y = spiral_data(samples=100,classes=3)

dense1 = Layer_Dense(n_inputs=2,n_neurons=3)

dense1.forward(X)

dense1.forward(X)

print(dense1.outputs[:5])



[[ 0.          0.          0.        ]
 [ 0.00010155  0.0002542  -0.00011534]
 [ 0.00019088  0.00044682 -0.00012087]
 [ 0.0002709   0.00061784 -0.00012105]
 [ 0.00039125  0.00101733 -0.00056212]]


#### **Implements of the ReLU and Sigmoid functions**

In [6]:
import numpy as np 

inputs  = [0,2,-1,3.3,-2.7,1.1,2.2,-100]

outputs = np.maximum(0,inputs)

print(outputs)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [7]:
## Activation function class

class Activation_ReLU:
    def forward(self,inputs):
        self.outputs = np.maximum(0,inputs)
        
    

In [8]:
inputs = [[1,2,3,2.5],
          [2,3,4,2.5],
          [3,4,5,2.5]]

# get unnormalized probability
exp_value = np.exp(inputs - np.max(inputs , axis = 1 , keepdims = True))

# get normalized probability
normalized_prob = exp_value / np.sum(exp_value , axis = 1 , keepdims = True)

print(normalized_prob)

np.sum(normalized_prob , axis = 1 , keepdims = True)

[[0.06414769 0.17437149 0.47399085 0.28748998]
 [0.07839412 0.2130973  0.57925853 0.12925005]
 [0.08536889 0.23205671 0.63079554 0.05177885]]


array([[1.],
       [1.],
       [1.]])

In [9]:
# softmax class
class Activation_Softmax:

    def forward(self, inputs):
        # get unnormalized probability
        exp_value = np.exp(inputs - np.max(inputs , axis = 1 , keepdims = True))

# get normalized probability
        normalized_prob = exp_value / np.sum(exp_value , axis = 1 , keepdims = True)

        self.output = normalized_prob

In [13]:
X ,y = spiral_data(samples=100, classes=3)

activation1 = Activation_ReLU()


activation2 = Activation_Softmax()


# create Dense layer with 2 inputs and 3 output values 

dense1 = Layer_Dense(2 , 3)

dense1.forward(X)

activation1.forward(dense1.outputs)

dense2 = Layer_Dense(3, 3)

dense2.forward(activation1.outputs)

activation2.forward(dense2.outputs)

print(activation2.output[:5])



# create ReLu activation function on dencse










[[0.33333333 0.33333333 0.33333333]
 [0.33333405 0.33333261 0.33333333]
 [0.33333413 0.33333295 0.33333292]
 [0.33333417 0.33333327 0.33333256]
 [0.3333334  0.33333352 0.33333308]]
