#### **create a categorical loss funtion**

In [1]:
import numpy as np

softmax_outputs = np.array([[0.1, 0.2, 0.7],
                            [0.2, 0.5, 0.3],
                            [0.4, 0.1, 0.5]])

class_target = np.array([2, 1, 2])
print(softmax_outputs[[0, 1, 2] , class_target])

[0.7 0.5 0.5]


In [2]:
print(-np.log(softmax_outputs[range(len(softmax_outputs)) , class_target]))

neg_log = -np.log(softmax_outputs[range(len(softmax_outputs)) , class_target])


average_loss = np.mean(neg_log)

print(average_loss)

[0.35667494 0.69314718 0.69314718]
0.5809897683528744


In [3]:
y_true_check = np.array([
    [0,0,1],
    [0,1,0],
    [0,0,1]

])

y_pred_clipped_check = np.array([[0.1, 0.2, 0.7],
                            [0.2, 0.5, 0.3],
                            [0.4, 0.1, 0.5]])

A = y_pred_clipped_check*y_true_check
B = np.sum(A, axis=1)
print(A)
print(B)

[[0.  0.  0.7]
 [0.  0.5 0. ]
 [0.  0.  0.5]]
[0.7 0.5 0.5]


In [4]:
neg_log = -np.log(B)
neg_log

array([0.35667494, 0.69314718, 0.69314718])

In [5]:
np.mean(neg_log)

np.float64(0.5809897683528744)

In [6]:


# final mean loss 
class Loss:
    def calculate(self , output ,y):
        sample_losses = self.forward(output , y)

        data_loss = np.mean(sample_losses)
        return data_loss
    



class Loss_CategoricalCrossentropy(Loss):
    def forward(self , y_pred , y_true):
        
        samples = len(y_pred)
        # clip the data to prevent divison by zero 
        # clip the both sides to not drag mean towards any vales 
        y_pred_clipped = np.clip(y_pred , 1e-7 , 1.0 - 1e-7)

        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples) , y_true]

        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped * y_true , axis = 1)

        # losses 
        negative_log_likelihood = -np.log(correct_confidences)

        return negative_log_likelihood
    

    
y_true_check = np.array([
    [0,0,1],
    [0,1,0],
    [0,0,1]

])

y_pred_clipped_check = np.array([[0.1, 0.2, 0.7],
                            [0.2, 0.5, 0.3],
                            [0.4, 0.1, 0.5]])


print(Loss_CategoricalCrossentropy().calculate(y_pred_clipped_check , y_true_check))



0.5809897683528744


#### **forward propagation to loss function**

In [7]:
!uv pip install nnfs 

Audited 1 package in 30ms


In [8]:
## Dence layer class 

from random import sample
import numpy as np
import matplotlib.pyplot as plt
from nnfs.datasets import spiral_data

In [9]:
class Layer_Dense:
    # layer initialization 
    def __init__(self,n_inputs,n_neurons):
        # initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs,n_neurons)
        # initialize biases 0
        self.biases = np.zeros([1,n_neurons])

    def forward(self,inputs):
        # forward pass
        self.outputs = np.dot(inputs,self.weights) + self.biases

## Activation function class

class Activation_ReLU:
    def forward(self,inputs):
        self.outputs = np.maximum(0,inputs)


# softmax class
class Activation_Softmax:

    def forward(self, inputs):
        # get unnormalized probability
        exp_value = np.exp(inputs - np.max(inputs , axis = 1 , keepdims = True))

# get normalized probability
        normalized_prob = exp_value / np.sum(exp_value , axis = 1 , keepdims = True)

        self.output = normalized_prob



In [10]:
X ,y = spiral_data(samples=100, classes=3)

activation1 = Activation_ReLU()


activation2 = Activation_Softmax()


# create Dense layer with 2 inputs and 3 output values 

dense1 = Layer_Dense(2 , 3)

dense1.forward(X)

activation1.forward(dense1.outputs)

dense2 = Layer_Dense(3, 3)

dense2.forward(activation1.outputs)

activation2.forward(dense2.outputs)


Loss_CategoricalCrossentropy_values = Loss_CategoricalCrossentropy()

Loss_values = Loss_CategoricalCrossentropy_values.calculate(activation2.output, y)

print("loss " , Loss_values)




## calculate aacuracy from output of activation funtion 

predictions =  np.argmax(activation2.output, axis=1)

if len(y.shape) == 2:
    y = np.argmax(y, axis=1)

accuracy = np.mean(predictions == y)


print("Accuracy " , accuracy)


loss  1.0986117993856384
Accuracy  0.33


#### **Accuracy**

In [12]:
import numpy as np

# probabilities of 3 samples 
softmax_outputs = np.array([[0.1, 0.2, 0.7],
                           [0.2, 0.5, 0.3],
                           [0.7, 0.3, 0.1]])

class_tragets = np.array([2, 1, 0])

predictions = np.argmax(softmax_outputs, axis=1)


if len(class_target.shape) == 2:
    class_target =  np.argmax(class_target, axis=1)
accuracy = np.sum(predictions == class_target) / predictions.shape[0]

print(accuracy)

0.6666666666666666
